In [1]:
import pickle
import numpy as np
from EM_MultivariateWatson import EM_MWD,matrix_vector_product

## Loading Data from Picke 

In [2]:
with open('.Data_LEiDA_Representation.pickle','rb') as f:
    X = pickle.load(f)

## EM algortihem

In [10]:
import pickle
import numpy as np
from EM_MultivariateWatson import EM_MWD,matrix_vector_product
with open('.Data_LEiDA_Representation.pickle','rb') as f:
    X = pickle.load(f)


X_test = X[:,0:331]
Pis,kappas,mus = EM_MWD(X_test,K=3,p=90,maxiter=10**3)

  0%|          | 0/1000 [00:00<?, ?it/s]/Users/magnusharder/Documents/UNI-DTU/4. Semester/Fagprojekt-f-mri/WatsonDistribution.py:72: RuntimeWarning: divide by zero encountered in double_scalars
  if (M_add)  / Mf < 1e-10:
 41%|████      | 407/1000 [03:49<05:37,  1.76it/s]

[[0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10540926]
 [0.10540926 0.10540926 0.10